baseurl = "https://d-dandrew.github.io"
title = "ddandrew's home site"

theme = "hugo-coder"

publishDir = "docs"

languagecode = "en-us"
defaultcontentlanguage = "zh-hans"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "yourdiscussshortname"

[params]
    ## Config these in the language sector
    author = "刘礼祥"
    description = "初生码农"
    keywords = "博客，开发者，游戏，科幻，个人"
    info = "初来乍到，承蒙款待"
    footercontent = "脚下有油"

    dateformat = "2006-01-02"

    avatarurl = "images/avatar.jpg"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

[taxonomies]
    series = "series"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/d-dandrew/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab"
    weight = 2
    url = "https://gitlab.com/d-dandrew/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/%E7%A4%BC%E7%A5%A5-%E5%88%98-bb037516a/"

[languages]
    [languages.en]
        languagename = "English"
        weight = 2
        contentDir = "content/english"


        [languages.en.params]
            author = "D_DAndrew"
            info = "D_DAndrew's personal website"
            description = "A new coder"
            keywords = "blog,developer,games,sci-fi,personal"
            footercontent = "Run fast"

            dateformat = "January 2, 2006"

            google_fonts_css_cdn= "https://fonts.googleapis.com/css?family=Lato:400,700%7CMerriweather:300,700%7CSource+Code+Pro:400,700"
            google_fonts_css_integrity = "sha384-UZhG5WipmU6WiF5wop3ssl1Wg0UEzv74OlREk8MniXxZPYlH4srr78D5Oye4n1xa"

            fontawesome_css_cdn= "https://use.fontawesome.com/releases/v5.3.1/css/all.css"
            fontawesome_css_integrity = "sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"

            normalize_css_cdn = "https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.min.css"
            normalize_css_integrity = "sha384-eYUmD1FFkORGrJdmrD37Z5LUEElTzF32+UI3jkzt7C1vpmUGo5KOVvb3Z5LeZHky"

            mathjax_js_cdn = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML-full"
            mathjax_js_integrity = "sha384-CABIusojVGLXKWOcdRP7wwh3SC7gjAbMmAnii19ZRH6QOsLiM6NIJ7Mb4BjfkQLU"

            katex_css_cdn = "https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/katex.min.css"
            katex_css_integrity = "sha384-dbVIfZGuN1Yq7/1Ocstc1lUEm+AT+/rCkibIcC/OmWo5f0EA48Vf8CytHzGrSwbQ"
            katex_js_cdn = "https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/katex.min.js"
            katex_js_integrity = "sha384-2BKqo+exmr9su6dir+qCw08N2ZKRucY4PrGQPPWU1A7FtlCGjmEGFqXCv5nyM5Ij"
            katex_autorender_js_cdn = "https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/contrib/auto-render.min.js"
            katex_autorender_js_integrity = "sha384-kWPLUVMOks5AQFrykwIup5lo0m3iMkkHrD0uJ4H5cjeGihAutqP0yW0J6dpFiVkI"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "/about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "/posts/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 3
            url = "/projects/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 4
            url = "/contact/"


    [languages.zh-hans]
        languagename = "中文"
        weight = 1
        contentDir = "content/chinese"
        title = "D_DAndrew 的主页"

        [languages.zh-hans.params]
            author = "D_DAndrew"
            info = "初来乍到，承蒙款待"
            description = "初生码农"
            keywords = "博客，开发者，游戏，科幻，个人"
            footercontent = "脚下有油"

            dateformat = "2006-01-02"

            google_fonts_css_cdn= "https://fonts.proxy.ustclug.org/css?family=Lato:400,700%7CMerriweather:300,700%7CSource+Code+Pro:400,700"
            google_fonts_css_integrity = "sha384-UZhG5WipmU6WiF5wop3ssl1Wg0UEzv74OlREk8MniXxZPYlH4srr78D5Oye4n1xa"

            fontawesome_css_cdn= "https://cdn.staticfile.org/font-awesome/5.3.1/css/all.min.css"
            fontawesome_css_integrity = "sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"

            normalize_css_cdn = "https://cdn.staticfile.org/normalize/8.0.0/normalize.min.css"
            normalize_css_integrity = "sha384-eYUmD1FFkORGrJdmrD37Z5LUEElTzF32+UI3jkzt7C1vpmUGo5KOVvb3Z5LeZHky"

            mathjax_js_cdn = "https://cdn.staticfile.org/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML-full"
            mathjax_js_integrity = "sha384-CABIusojVGLXKWOcdRP7wwh3SC7gjAbMmAnii19ZRH6QOsLiM6NIJ7Mb4BjfkQLU"

            katex_css_cdn = "https://cdn.staticfile.org/KaTeX/0.10.1/katex.min.css"
            katex_css_integrity = "sha384-dbVIfZGuN1Yq7/1Ocstc1lUEm+AT+/rCkibIcC/OmWo5f0EA48Vf8CytHzGrSwbQ"
            katex_js_cdn = "https://cdn.staticfile.org/KaTeX/0.10.1/katex.min.js"
            katex_js_integrity = "sha384-2BKqo+exmr9su6dir+qCw08N2ZKRucY4PrGQPPWU1A7FtlCGjmEGFqXCv5nyM5Ij"
            katex_autorender_js_cdn = "https://cdn.staticfile.org/KaTeX/0.10.1/contrib/auto-render.min.js"
            katex_autorender_js_integrity = "sha384-kWPLUVMOks5AQFrykwIup5lo0m3iMkkHrD0uJ4H5cjeGihAutqP0yW0J6dpFiVkI"

        [languages.zh-hans.menu]

            [[languages.zh-hans.menu.main]]
            name = "关于"
            weight = 1
            url = "/about/"

            [[languages.zh-hans.menu.main]]
            name = "博客"
            weight = 2
            url = "/posts/"

            [[languages.zh-hans.menu.main]]
            name = "项目"
            weight = 3
            url = "/projects/"

            [[languages.zh-hans.menu.main]]
            name = "联系"
            weight = 4
            url = "/contact/"